steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/seo-agent-frontend:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '.'